### ISSUE TITLE
large heading not readable in mobile view

### ISSUE THREAD

**Issue by Raunaksingh100** [inclusive-design/wecount.inclusivedesign.ca#345] opened 2020-07-27 10:34 UTC
## Describe the bug

The size of the h1 (Which is "Creating an inclusive data ecosystem") is two large **not readable** in  mobile view ###the changed to be small.......

## To Reproduce

1. Go to 'https://wecount.inclusivedesign.ca/'
2. Click on 'homepage'
3. See error

## Screenshots before---
![h1 eerr](https://user-images.githubusercontent.com/65535360/88532667-9d9d0400-d022-11ea-9186-f883710e4869.PNG)

after---
![h1 fixed](https://user-images.githubusercontent.com/65535360/88532693-a7266c00-d022-11ea-8a1f-8602abfe6513.PNG)

## Smartphone (please complete the following information):

- Device: [e.g. iPhone6 , 5 , 6s]
- Browser [e.g. stock browser

## Additional context--
@cindyli @greatislander @gtirloni 
i already fixed this issue here the link of my pr

**Comment by cindyli** [comment] 2020-07-27 13:43
Closed as this is a duplicate of #322 that has been fixed a couple of days ago.

@Raunaksingh100, you can check the fix at [the WeCount dev deploy](https://dev--wecount.netlify.app/).

**Closed by cindyli** 2020-07-27 13:43 UTC
Labels: bug

**Comment by Raunaksingh100** [comment] 2020-07-27 13:59
@cindyli  what about this link https://wecount.inclusivedesign.ca/
there is still h1 problem

**Comment by cindyli** [comment] 2020-07-27 14:12
@Raunaksingh100 what you pointed to is [the production site](https://wecount.inclusivedesign.ca/) that will only be updated at production releases. At this point, the fix for #322 has been merged into the dev branch and is waiting for the next 2.2 release, which hopefully will happen soon.
