### ISSUE TITLE
Pagination Styling 

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#129] opened 2020-03-28 20:18 UTC
## Describe the bug

The styling for the pagination component is now available in the [Figma](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=684%3A883) file.

Add These styles to the We Count website

## To Reproduce

n/a

## Expected behavior

Should look the same as [Figma](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=684%3A883).

**Comment by greatislander** [comment] 2020-03-28 20:20
@TeddTech This looks like a duplicate of https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/123.

**Closed** 2020-03-28 20:49 UTC
Labels: bug
